#!/bin/sh

# Startup commands
pidof -sx picom || picom --experimental-backends &
pidof -sx sxhkd || sxhkd &
pidof -sx dunst || dunst &
# Initialize desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Global settings
bspc config normal_border_color    "#4a4a4a"
bspc config active_border_color    "#848484"
bspc config focused_border_color   "#bcecff"
bspc config split_ratio            0.52
bspc config borderless_monocle     false
bspc config gapless_monocle        true
bspc config single_monocle         true
bspc config pointer_modifier       mod4
bspc config pointer_action1        move
bspc config pointer_action2        resize_corner
bspc config focus_follows_pointer  true

# Desktop settings
bspc config window_gap 16

# Node settings
bspc config border_width 1

# Rules
bspc rule -a flameshot border=off
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a code desktop='^2' follow=on
bspc rule -a thunar desktop='^4' follow=on
bspc rule -a Spotify desktop='^9'
bspc rule -a ts3client_linux_amd64 desktop='^10' state=floating
bspc rule -a Alacritty desktop='^1' follow=on
bspc rule -a virt-manager desktop='^5' follow=on
# Set wallpapper
feh --bg-fill $HOME/.config/wallpapper.png

# Autostart
# Remove mouse acceleration
xinput set-prop 16 298 -1 &
# Set keyboard layout
setxkbmap -layout us -variant intl &
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Launch polybar
~/.config/polybar/launch.sh &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Spotify
spotify &
# Teamspeak
teamspeak3 &